### PR TITLE
Automatically generate default `exec_root` path

### PR DESCRIPTION
**Pull request by xiay-nv**
`exec_root` is used as the `directory` field in the produced compile
command database, which must be an absolute path of the local file
system.  Specifying a fixed absolute path in the repository
significantly reduce the portability of the develop environemnt,
virtually requires the repository to be compiled in a fixed container
setup.

This change use shell command-line to automatically generate
`exec_root` path when no value is explicitly specified, which avoids
above limitation.

Due to the extreme difficulty of retrieving real filesystem absolute
path inside bazel script.  The path is retrieved from working path
from in shell script through `run_shell` action.  This approach
relies on the relative path from sandbox execution path to workspace
execution path, which may be changed in future bazel versions.

### CODE REVIEW

**Comment by siddharthab** [comment]
Thank you for the change. While I agree with the spirit of the change, I feel like the current implementation is slightly brittle and hard to read, as you have mentioned in your comments. FWIW, our `generate.sh` script is also hacky, but I would like to not introduce more, and in principle, we could simplify the generate.sh script but we would not have clear paths forward here.

Let me think if there is a better way of detecting the exec root. For source directory, we take the root workspace file as a label attribute, and follow symlinks to that. For execroot, we would have to take a generated file as an input to this rule, like how you are doing with `__main__`.

When I initially wrote this rule, I thought the simplest way would be for people to wrap the bazel invocation in a shell script that would use sed to replace the marker with the actual location. Similar to what we do in `generate.sh`. Would it help if this project provided a template script for this purpose?

**Comment by siddharthab** [comment]
Hello!

I have updated the [README](https://github.com/grailbio/bazel-compilation-database#selected-targets) with better instructions on how to use the selected targets mode. Perhaps that will clarify the expected usage pattern here.

Please let me know if it is sufficient for you.

We can then review the `filter_flags` change separately.

Thanks!

**Comment by xiay-nv** [comment]
Thanks for the clarification.  However manual step outside bazel is undesired in our step thus this may not be as useful.

**Comment by xiay-nv** [comment]
Actually the hacky part of my `realpath` command could be removed by using `execution_requirements`:  https://stackoverflow.com/a/48551327/3466604, where we no longer need to get rid of the relative path of sandbox.

**Comment by xiay-nv** [comment]
@siddharthab 
I have completely reworked the MR to use repository_rule to access results from shell command and filesystem for the calculation of `exec_root` path.  It still relies on the fact that an external repository is placed at `<build_root>/external/<repo_name>` while `exec_root` being `<build_root>/execroot/<workspace_name>`.  I think this part should be a much stable layout for bazel than the previous sandbox path.

I also took the liberty to move `filter_flags` to the same virtual repo so flag filtering could happen in the very first place also.

Added `clang_tidy_test` to show case how I envision the update aspect could be used.

Since this is now a full bazel solution as `clang_tidy_test` use case would show, script `generate.sh` shall no longer be needed.  However I do not quite understand the `bazel build` command in the `generate.sh` script and why it failed.  Maybe you could shed some light here?

**Comment by siddharthab** [comment]
Thanks for your continued efforts on this. I will take a look this weekend.

**Comment by dhmemi** [comment]
will this MR be merged ?

**Comment by siddharthab** [comment]
My apologies for the delay in getting to this PR.

With 0.5.1, I have now included the changes to support the clang-tidy check as you want it:
1. There is now an OUTPUT_BASE value that you can supply to the compilation_database rule to set the right compilation directory. More details in the README.
2. The aspect output group is now returning the direct source files of a target.
3. For filter_flags, I felt that it could be too specific to an application, and so should be handled at that level. In your case, you can remove the filter_flags strings from the compilation database json before using it with clang-tidy. If this is not enough, then maybe we can open a new PR with just that feature.

I think the clang-tidy check rule itself should be better off in a new repo, as it is a very specific application. I think I am exporting everything that you would need. If you do create such a repo, please let me know and I can advertise it here.

I am going to close this PR now. Thank you so much for your efforts.

**Pull request closed without merging**
