### PR TITLE
Update for bazel 0.27.0

### PR DESCRIPTION
**Pull request by keith**
This is required as of bazel 0.27.0 https://github.com/bazelbuild/bazel/issues/7793

### CODE REVIEW

**Comment by keith** [comment]
The test failure here doesn't _appear_ to be related to this change, but I'm not sure why it's red but master is green

**Comment by soonho-tri** [comment]
@keith , could you also add the following to make it work with bazel-0.27.0?

```diff
diff --git a/aspects.bzl b/aspects.bzl
index de71af6..9419950 100644
--- a/aspects.bzl
+++ b/aspects.bzl
@@ -73,9 +73,9 @@ def _is_objcpp_target(srcs):
 def _sources(target, ctx):
     srcs = []
     if "srcs" in dir(ctx.rule.attr):
-        srcs += [f for src in ctx.rule.attr.srcs for f in src.files]
+        srcs += [f for src in ctx.rule.attr.srcs for f in src.files.to_list()]
     if "hdrs" in dir(ctx.rule.attr):
-        srcs += [f for src in ctx.rule.attr.hdrs for f in src.files]
+        srcs += [f for src in ctx.rule.attr.hdrs for f in src.files.to_list()]

     if ctx.rule.kind == "cc_proto_library":
         srcs += [f for f in target.files if f.extension in ["h", "cc"]]
```

**Comment by keith** [comment]
I've added those but also another case, I hadn't run with this yet, thanks! I'm still trying to get CI green too

**Comment by keith** [comment]
Alright we're all green here now!

**Comment by keith** [comment]
I'm also testing this update on Envoy https://github.com/envoyproxy/envoy/pull/7391

**Comment by soonho-tri** [comment]
Nice, thanks!

**Comment by keith** [comment]
Any chance this could get merged and a new release can be cut? The former being more important to us so we don't have to point to my short-term fork

**Comment by siddharthab** [comment]
Thank you everyone for your help in maintaining this project.

I have tried to set up bazelisk for this project so I can catch upcoming breaking changes, but have not got around to github API limits for getting bazel releases and issue list.

**Comment by keith** [comment]
@siddharthab I just added bazelisk support for a github API token to work around this https://github.com/bazelbuild/bazelisk/pull/62 so you should be able to do that now!

**Comment by siddharthab** [comment]
Oh awesome! Thanks. I will update this project to start using bazelisk, and ask Travis to run the tests at least once every week to learn about upcoming breaking changes.

This pull request is now included in release 0.3.5.

**Pull request merged**
