### PR TITLE
Also collect source files from non_arc_srcs attributes

### PR DESCRIPTION
**Pull request by efyx**
Our code is using the `obc_library()` rule along with the `non_arc_srcs` attributes which aren't collected as sources files by `bazel-compilation-database`. This PR simply add the sources files in `non_arc_srcs` to the list of sources files to process by the compilation db script.

**Note**: This is partially working as while non ARC files are collected they are still compiled with `-fobjc-arc` here https://github.com/grailbio/bazel-compilation-database/blob/master/aspects.bzl#L237-L238 . Any idea what would be the best way to handle that?

### CODE REVIEW

**Comment by siddharthab** [comment]
Apologies for the delay. It looks like I don't have permissions to force push to the pull request branch. I have refactored the code such that you can now specify `-fobjc-arc` at a file-level.

Your PR can now effectively be the following diff:
```
$ git diff -U1 HEAD~1
diff --git a/aspects.bzl b/aspects.bzl
index 8867f7a..10c4562 100644
--- a/aspects.bzl
+++ b/aspects.bzl
@@ -205,2 +205,7 @@ def _objc_compile_commands(ctx, target, feature_configuration, cc_toolchain):
 
+    non_arc_srcs = []
+    if "non_arc_srcs" in dir(ctx.rule.attr):
+        non_arc_srcs += [f for src in ctx.rule.attr.non_arc_srcs for f in src.files.to_list()]
+    srcs.extend(non_arc_srcs)
+
     # We currently recognize an entire target as objective-c++ or not. This can
@@ -242,5 +247,2 @@ def _objc_compile_commands(ctx, target, feature_configuration, cc_toolchain):
 
-    # TODO: This needs to be per-file.
-    compile_flags.append("-fobjc-arc")
-
     compile_flags.extend(ctx.rule.attr.copts if "copts" in dir(ctx.rule.attr) else [])
@@ -262,4 +264,5 @@ def _objc_compile_commands(ctx, target, feature_configuration, cc_toolchain):
     for src in srcs:
+        arc_flag = "" if src in non_arc_srcs else " -fobjc-arc"
         compile_commands.append(struct(
-            cmdline = cmdline + " -c " + src.path,
+            cmdline = cmdline + arc_flag + " -c " + src.path,
             src = src,
```

I will merge when the PR has been updated. Thanks!

**Comment by siddharthab** [comment]
I am going to try to land the rebased solution directly on the master branch.

**Comment by siddharthab** [comment]
Looks like it worked. I will close this PR now.

**Comment by efyx** [comment]
Thanks for the update/changes @siddharthab the changes looks good 👍

**Pull request closed without merging**
