### PR TITLE
Objective C/C++ support

### PR DESCRIPTION
**Pull request by jfaust**
I'm not sure if this is in a shape where you'll accept it as-is. Honestly I'm hoping there's actually a much better way to do this - but the Objective-C/C++ rules don't seem to provide an equivalent to `target.cc.compile_flags`. It's further complicated by the fact that the only thing that knows the Xcode SDKROOT is `XcodeLocalEnvProvider`, and I could not find a way to access the environment it sets.

### CODE REVIEW

**Comment by siddharthab** [comment]
Sorry for the delay in my response.

I have pushed an update to run the latest buildifier on the files, and also made the tests pass on bazel 0.22.0. Can you please rebase your branch?

I think your changes are fine. Can you refactor such that the logic for cc_ and objc_ rules are in two separate functions? Just for readability.

After you are done, I may push a commit to your branch before merging, for minor formatting nits.

Thank you for your contribution.

**Comment by jfaust** [comment]
Will do - may take me a few days.

**Comment by jfaust** [comment]
@siddharthab more than the few days I promised, but I've rebased and factored out the handling of cc_ and objc_ rules into separate functions.

**Comment by siddharthab** [comment]
Thank you! The code looks clean now.

I could not do a thorough review of the ObjC portion because I have never worked with it. I trust that you have tested these changes. Ideally, a unit test would be nice but I am happy to add the unit test as a separate merge.

**Pull request merged**
