### PR TITLE
handle generated headers and virtual_includes via output_group

### LINKED ISSUE #29: Handle strip_include_prefix and include_prefix attributes
These attributes use the _virtual_includes directory which is not materialized outside of the sandbox.

In this scenario, the command line generated from this project will work when `--spawn_strategy=standalone` was used when building the cc_* targets, but not without it.

Thanks @FaBrand for noticing this.

Related issues elsewhere:
https://github.com/bazelbuild/intellij/issues/145
https://github.com/bazelbuild/intellij/issues/510

### PR DESCRIPTION
**Pull request by lizan**
Define a output group `header_files` contains all headers needed by the target including generated ones, virtual_includes. This will let Bazel generate header files when necessary (for example, `cc_proto_library`), and setup `virtual_includes` directories as well.

Fixes #29. 

Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by lizan** [comment]
CI failure looks unrelated

**Comment by siddharthab** [comment]
Thanks for the change! I am surprised it was really this simple.

CI tests are good. I have to make the macOS tests more robust to XCode version changes. Also, migration tests always fail because of the way bazelisk fetches the list of flags; I have to check if there is a better way to check that.

I will take a more detailed look in a bit.

**Comment by lizan** [comment]
Yeah I was surprised too when I was look into this. This make our compilation generation much faster. We used to run bazel build before generation just to make sure headers are generated.

**Comment by siddharthab** [comment]
Sorry, I force pushed a commit fixing the commit message in the original commit. That's why the PR shows two commits.

**Comment by siddharthab** [comment]
Thanks @lizan !

**Comment by lizan** [comment]
No worries, thanks for merging!

**Pull request merged**
