### PR TITLE
Minor refactorings and improvements

### PR DESCRIPTION
**Pull request by FaBrand**
Changes:
- Change nested test loop to use any()
- Enhance error message in case file is not referenced in bazel
- Enhance error output if bazel build step fails to show only errors
- Update Plugged part of readme

### CODE REVIEW

**Comment by siddharthab** [comment]
Thank you for your pull request. I will review it over the weekend or early next week.

**Comment by siddharthab** [comment]
Sorry for the delay. I looked into it a little bit more, and it appears that the `include_prefix` and `strip_include_prefix` attributes are not that straight forward.

At compile time, bazel creates a `_virtual_includes` directory with symlinks to the right files. This directory is gone when the sandbox is deleted. The current code works when giving `--spawn_strategy=standalone` while building because the include paths contain virtual_includes

Your suggested change will work for some cases in `strip_include_prefix`, but not all. And there seems to be no easy way to handle `include_prefix`. Let me see if we can somehow retain or recreate the virtual_includes directory. Most likely, the answer to this is no.

Let's merge your changes 1-4 separately from your `strip_include_prefix` change. If you can send me a new PR for 1-4, it will be appreciated, else I can merge a separate commit with you as the author. For `strip_include_prefix`, let's make sure that we handle all the cases that we can.

**Comment by FaBrand** [comment]
Thanks for your feedback. 
Fine for me, i removed the strip_include_prefix part and amended the commit to show what it actually does. Could you point out the cases that didn't work for you? I would like to understand what i missed :)
So maybe i can have another look at it and maybe came back at a later point in time

**Comment by siddharthab** [comment]
Thank you so much for understanding.

For 'strip_include_prefix', I think we were missing handling absolute paths.
I am going to file a feature request in bazel to also materialize the _virtual_includes directory in bazel-bin. That solves all problems, but I doubt it will happen any time soon. There are existing issues about this problem in other projects:
https://github.com/bazelbuild/intellij/issues/145
https://github.com/bazelbuild/intellij/issues/510

**Comment by siddharthab** [comment]
Opened #29.

**Pull request merged**
